services:
  - type: web
    name: criss-ai-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: AUTO_STATUS_REACT
        value: "true"
        generateValue: false
      - key: AUTO_STATUS_SEEN
        value: "true"
        generateValue: false
      - key: AUTO_TYPING
        value: "false"
        generateValue: false
      - key: OWNER_NAME
        value: "CRISS VEVO"
        generateValue: false
      - key: OWNER_NUMBER
        value: "255687068672"
        generateValue: false
      - key: SESSION_ID
        value: ""
        generateValue: false
