services:
  - type: web
    name: CRISS-AI
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    envVars:
      - key: SESSION_ID
        value: true
      - key: OWNER_NUMBER
        value: true
