```yaml
services:
  - type: web
    name: CRISS-AI
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    envVars:
      - key: SESSION_ID
        value: "your-session-id-here"
      - key: OWNER_NUMBER
        value: "your-owner-number-here"
```
