services:
  - type: web
    name: criss-ai
    env: .env
    plan: free
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
        - .dockerignore
        - src/**
        - package.json
        - package-lock.json
